### ISSUE TITLE
KeyError: 'containerStatuses'

### ISSUE THREAD

**Issue by vadorovsky** [cilium/cilium-sysdump#72]
When running cluster-diagnosis on Cilium 1.6.5 and k8s  1.17.0

```
devel@bpf-devel:~> curl -sLO releases.cilium.io/tools/cluster-diagnosis.zip
devel@bpf-devel:~> python cluster-diagnosis.zip sysdump
INFO collecting kubernetes version info ...
INFO collected kubernetes version info: k8s-version-info-20200109-140027.txt
INFO collecting Kubernetes events JSON ...
INFO collected kubernetes events: k8s-events-20200109-140027.json
INFO collecting nodes overview ...
INFO collected nodes overview: nodes-20200109-140028.json
INFO collecting pods overview ...
INFO collected pods overview: pods-20200109-140028.json
INFO collecting pods summary ...
INFO collected pods summary: pods-20200109-140028.txt
INFO collecting services overview ...
INFO collected svc overview: services-20200109-140028.yaml
INFO collecting cilium gops stats ...
INFO collected gops stats file: cilium-5pjbj-20200109-140028-stats.txt
INFO collected gops memstats file: cilium-5pjbj-20200109-140028-memstats.txt
INFO collected gops stack file: cilium-5pjbj-20200109-140029-stack.txt
INFO collecting kubernetes network policy ...
INFO collected kubernetes network policy: netpol-20200109-140029.yaml
INFO collecting cilium network policy ...
INFO collected cilium network policy: cnp-20200109-140029.yaml
INFO collecting cilium etcd secret ...
Error from server (NotFound): secrets "cilium-etcd-secrets" not found
ERROR Error: Command 'kubectl get secret cilium-etcd-secrets -n kube-system -o json' returned non-zero exit status 1. Unable to get and redact cilium secret
INFO collecting cilium endpoints ...
INFO collected cilium endpoints: cep-20200109-140029.yaml
INFO collecting cilium daemonset yaml ...
INFO collected cilium daemonset yaml file: cilium-ds-20200109-140029.yaml
INFO collecting cilium configmap yaml ...
INFO collected cilium configmap yaml file: cilium-configmap-20200109-140029.yaml
INFO collecting cilium-bugtool output ...
Skipping directory cilium-bugtool-20200109-130030.269+0000-UTC-904438321
Skipping directory cmd
Skipping directory state
Skipping directory 1286_next
Skipping directory 1286_next_fail
Skipping directory 1687_next_fail
Skipping directory 395_next
Skipping directory 395_next_fail
Skipping directory globals
Skipping directory templates
Skipping directory e5b5f92f0eb7770a6e891c3606f51c0776f4b90c
Skipping directory conf
INFO collected cilium-bugtool output: bugtool-cilium-5pjbj-20200109-140030.tar
INFO collecting cilium logs ...
INFO collected log file: cilium-5pjbj-20200109-140032
DEBUG no previous pod logs to gather for pod cilium-5pjbj
INFO collected log file: cilium-operator-55658fb5c4-gxzlm-20200109-140033
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "cluster-diagnosis.zip/__main__.py", line 115, in <module>
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 448, in collect
  File "cluster-diagnosis.zip/sysdumpcollector.py", line 104, in collect_logs
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'containerStatuses'
```

**Comment by michi-covalent** [comment]
we are migrating to a new implementation of sysdump `cilium sysdump`: https://github.com/cilium/cilium-cli could you try the new command and open an issue in the cilium-cli repo if you continue to experience the same issue? thanks!
